language: php

php:
  - '5.6'

before_script:
  - sh .travis.install.sh

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover tests/coverage.xml

#script:
#  - ./vendor/bin/phpunit
